### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bbauley** [a5huynh/defender-game#1]
Hello Mr. Huynh, 

I'm currently needing to build some sort of project for my Rust Programing class. I'm planning on building a simple snake game and I like your article that you wrote along with your code structure for the 2D defender game. Do you mind if I go off of your structure and modify it to work for a snake game? I will add your article link as a resource, I just wanted a confirmation since you don't have any licensing for the project.

Thanks,
Brandon Bauley

**Comment by a5huynh** [comment]
@bbauley absolutely! 

Feel free to fork and use whatever you want of the project. I'll update the repo with a basic license file as well.

**Comment by bbauley** [comment]
Perfect! Thanks a lot.
